### ISSUE TITLE
Suggested documentation update

### ISSUE THREAD

**Issue by sylnsr** [avinetworks/ansible-role-docker#4]
On Ubuntu 16.04 with Ansible 2.3, the install fails unless `gather_facts: true` is set.
The documentation should reflect this is required ... even if just in this case.

**Comment by ericsysmin** [comment]
It's not caused by the role. You're hitting an Ansible issue itself. Even the 
```
- hosts: all
  tasks:
    - ping:
```

Will fail. it's because Ubuntu 16.04 doesn't use Python2 which Ansible is set for default. 

https://stackoverflow.com/questions/32429259/ansible-fails-with-bin-sh-1-usr-bin-python-not-found

Another valid solution:
ansible my_ubuntu_host -m ping -e 'ansible_python_interpreter=/usr/bin/python3'

**Comment by ericsysmin** [comment]
Also by default gather_facts: true should be set. If it is not then your install of Ansible is broken. 

```

# plays will gather facts by default, which contain information about
# the remote system.
#
# smart - gather by default, but don't regather if already gathered
# implicit - gather by default, turn off with gather_facts: False
# explicit - do not gather by default, must say gather_facts: True
#gathering = implicit
```
extracted from `ansible.cfg`

**Comment by sylnsr** [comment]
@ericsysmin, setting one of these other valid options in ansible.cfg merely makes it a non-default Ansible config. It does not make Ansible "broken".

**Comment by sylnsr** [comment]
Also, regarding "Ubuntu 16.04 doesn't use Python2" .. the [recommended solution from the Ansible project is to install it](https://github.com/ansible/ansible/issues/17081#issuecomment-301649141) .. as opposed to defining Python 3 as the Ansible Python interpreter. I don't currently see that anything has changed since that posting.
